In [1]:
from lib import classification as c
import joblib

import numpy as np
import pandas as pd

from sklearn.svm import LinearSVC
from sklearn import cross_validation                                        
from sklearn import svm   
from sklearn import metrics
from sklearn.ensemble import RandomForestRegressor
from sklearn import cross_validation                                           
from sklearn import svm                                                        

In [20]:
train_data = c.getTrainData(False) #Pass True to this function to re-train!

In [21]:
X_train, X_test, y_train, y_test = cross_validation.train_test_split(
    train_data[0], train_data[1], test_size=0.3, random_state=0)

weights = c.getClassWeights() 

Counter({1: 433, 0: 407, 2: 232})


## Linear SVM

In [22]:
clf = LinearSVC(class_weight=weights)
clf.fit(X_train, y_train)

#Perform classification on train test split
y_pred = clf.predict(X_test)
print metrics.classification_report(y_test, y_pred)

#Perform 5 fold crossval
clf = svm.SVC(kernel='linear', C=1)                                            
scores = cross_validation.cross_val_score(clf, train_data[0], train_data[1], cv=5)  
print '5 Fold CrossValidation Score \n'
print scores

             precision    recall  f1-score   support

          0       1.00      1.00      1.00       110
          1       1.00      1.00      1.00       140
          2       1.00      1.00      1.00        72

avg / total       1.00      1.00      1.00       322

5 Fold CrossValidation Score 

[ 1.  1.  1.  1.  1.]


In [23]:
#With Final Test Data
clf = LinearSVC()
clf.fit(X_train, y_train)
report, df = c.predict(clf,True)
print report

started extracting feautes
done extracting features
             precision    recall  f1-score   support

          0       1.00      0.89      0.94         9
          1       0.89      1.00      0.94         8
          2       1.00      1.00      1.00         8

avg / total       0.96      0.96      0.96        25



## Logistic

In [9]:
from sklearn import linear_model

In [10]:
clf = linear_model.LogisticRegression(class_weight=weights)

In [11]:
clf.fit(X_train, y_train)

#Perform classification on train test split
y_pred = clf.predict(X_test)
print metrics.classification_report(y_test, y_pred)

#Perform 5 fold crossval
clf = svm.SVC(kernel='linear', C=1)                                            
scores = cross_validation.cross_val_score(clf, train_data[0], train_data[1], cv=5)  
print '5 Fold CrossValidation Score \n'
print scores

             precision    recall  f1-score   support

          0       1.00      1.00      1.00       110
          1       1.00      1.00      1.00       140
          2       1.00      1.00      1.00        72

avg / total       1.00      1.00      1.00       322

5 Fold CrossValidation Score 

[ 1.  1.  1.  1.  1.]


In [12]:
# Test with separate test data
clf = linear_model.LogisticRegression(class_weight=weights)

clf.fit(X_train, y_train)
report, df = c.predict(clf,True)
print report

started extracting feautes
done extracting features
             precision    recall  f1-score   support

          0       1.00      0.89      0.94         9
          1       0.89      1.00      0.94         8
          2       1.00      1.00      1.00         8

avg / total       0.96      0.96      0.96        25



### Random Forest

In [13]:
# Estimate the score on the entire dataset, with no missing values
clf = RandomForestRegressor(random_state=0, n_estimators=100)

In [14]:
clf.fit(X_train, y_train)

#Perform classification on train test split
y_pred = clf.predict(X_test)
metrics.classification_report(y_test, y_pred)

#Perform 5 fold crossval
clf = svm.SVC(kernel='linear', C=1)                                            
scores = cross_validation.cross_val_score(clf, train_data[0], train_data[1], cv=5)  
print '5 Fold CrossValidation Score \n'
print scores

ValueError: Mix type of y not allowed, got types set(['continuous', 'multiclass'])

In [15]:
# Test with separate test data
clf.fit(X_train, y_train)
report, df = c.predict(clf)
print report

ValueError: Mix type of y not allowed, got types set(['continuous', 'multiclass'])

### SVM RBF

In [16]:
clf = svm.NuSVC(kernel="rbf")

In [17]:
clf.fit(X_train, y_train)

#Perform classification on train test split
y_pred = clf.predict(X_test)
print metrics.classification_report(y_test, y_pred)

#Perform 5 fold crossval
clf = svm.SVC(kernel='linear', C=1)                                            
scores = cross_validation.cross_val_score(clf, train_data[0], train_data[1], cv=5)  
print '5 Fold CrossValidation Score \n'
print scores

             precision    recall  f1-score   support

          0       1.00      1.00      1.00       110
          1       1.00      1.00      1.00       140
          2       1.00      1.00      1.00        72

avg / total       1.00      1.00      1.00       322

5 Fold CrossValidation Score 

[ 1.  1.  1.  1.  1.]


In [18]:
# Test with separate test data
clf = svm.NuSVC(kernel="rbf")
clf.fit(X_train, y_train)
report, df = c.predict(clf, True)
print report

started extracting feautes
done extracting features
             precision    recall  f1-score   support

          0       1.00      0.89      0.94         9
          1       0.89      1.00      0.94         8
          2       1.00      1.00      1.00         8

avg / total       0.96      0.96      0.96        25



### Detect Outliers
Inliers are labeled 1, while outliers are labeled -1

In [26]:
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.font_manager
from sklearn import svm

In [27]:
# fit the model
clf = svm.OneClassSVM(nu=0.1, kernel="rbf", gamma=0.1)
clf.fit(X_train)
y_pred_train = clf.predict(X_train)
y_pred_test = clf.predict(X_test)

In [28]:
y_pred_outliers = clf.predict(X_outliers)

NameError: name 'X_outliers' is not defined

In [29]:
from collections import Counter                                             
t = Counter(y_pred_test)   
tr = Counter(y_pred_train)  
print t
print tr

Counter({1.0: 291, -1.0: 31})
Counter({1.0: 675, -1.0: 75})


In [30]:
print float(t[1]) / sum(t.values())*100
print float(tr[1]) / sum(tr.values())*100

90.3726708075
90.0


In [31]:
test_d = c.getTestData()

In [32]:
y_pred_test = clf.predict(test_d[0])

In [33]:
t = Counter(y_pred_test)  
print float(t[1]) / sum(t.values())*100


72.0


In [38]:
outlier = c.getOutlierData()
o = clf.predict(outlier)
print o

started extracting feautes
done extracting features
[-1.  1.  1.  1.  1.]


In [40]:
o = Counter(o)

In [41]:
print float(o[-1]) / sum(o.values())*100

20.0


In [47]:
X_outliers = c.getOutlierData()

# fit the model
clf = svm.OneClassSVM(nu=0.1, kernel="rbf", gamma=0.1)
clf.fit(X_train)
y_pred_train = clf.predict(X_train)
y_pred_test = clf.predict(X_test)
y_pred_outliers = clf.predict(X_outliers)
n_error_train = y_pred_train[y_pred_train == -1].size
n_error_test = y_pred_test[y_pred_test == -1].size
n_error_outliers = y_pred_outliers[y_pred_outliers == 1].size



started extracting feautes
done extracting features
